id: P008134
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:03:48.377060
source_metadata:
  id: bdr:W3CN4918
  title: སྨྱུང་གནས་ཀྱི་རྣམ་བཤད་དང་ཕན་ཡོན་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    d166969c399e48a0a55c333c58f32c72:
      image_group_id: I3CN4920
      title: Volume 1 of bsnyung gnas kyi rnam bshad dang phan yon skor phyogs bsgrigs/
      volume_number: 1
      total_pages: 398
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
