id: P008134
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4918
  title: སྨྱུང་གནས་ཀྱི་རྣམ་བཤད་དང་ཕན་ཡོན་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    68f5eca2dfe3432f911fb2bed18e18d7:
      image_group_id: I3CN4920
      title: ''
      volume_number: 1
      total_pages: 398
ebook_metadata:
  title: སྨྱུང་གནས་ཀྱི་རྣམ་བཤད་དང་ཕན་ཡོན་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P008134
  cover: cover.jpg
  layers:
  - pagination
