id: opecha:P008134
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4918
  title: སྨྱུང་གནས་ཀྱི་རྣམ་བཤད་དང་ཕན་ཡོན་སྐོར་ཕྱོགས་བསྒྲིགས།
  volume:
    d166969c399e48a0a55c333c58f32c72:
      image_group_id: I3CN4920
      title: Volume 1 of bsnyung gnas kyi rnam bshad dang phan yon skor phyogs bsgrigs/
      volume_number: 1
      total_pages: 398
  author: ''
ebook_metadata:
  title: སྨྱུང་གནས་ཀྱི་རྣམ་བཤད་དང་ཕན་ཡོན་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P008134
  cover: cover.jpg
  layers:
  - pagination
